/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

/**
 *
 * @author AULA4
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import AppPackage.AnimationClass;
import conexion.Conectar;
import javax.swing.JOptionPane;
import org.postgresql.util.PSQLException;

public class agregarProo extends javax.swing.JFrame {
   public Conectar manejador = new Conectar();
   private Connection connection = null;
   private Statement s = null;
   
    public agregarProo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        bocciones = new javax.swing.JLabel();
        jlhomee = new javax.swing.JLabel();
        jlatras = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        nombreProv = new javax.swing.JTextField();
        marcaProv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        telefonoProv = new javax.swing.JTextField();
        codigoProv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        bminimizar = new javax.swing.JLabel();
        bquitar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setMinimumSize(new java.awt.Dimension(715, 428));
        jPanel2.setPreferredSize(new java.awt.Dimension(715, 428));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(673, 342));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(400, 376));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 32));
        jPanel7.setPreferredSize(new java.awt.Dimension(50, 426));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bocciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Menu_32px_1.png"))); // NOI18N
        bocciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boccionesMouseClicked(evt);
            }
        });
        jPanel7.add(bocciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 22));

        jlhomee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlhomee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/inicio.png"))); // NOI18N
        jlhomee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlhomeeMouseClicked(evt);
            }
        });
        jPanel7.add(jlhomee, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 50, 40, 30));

        jlatras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/regresar.png"))); // NOI18N
        jlatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlatrasMouseClicked(evt);
            }
        });
        jPanel7.add(jlatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 90, 40, 30));

        jPanel5.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreProv.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        nombreProv.setBorder(null);
        nombreProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProvActionPerformed(evt);
            }
        });
        jPanel6.add(nombreProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 180, 30));

        marcaProv.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        marcaProv.setBorder(null);
        marcaProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaProvActionPerformed(evt);
            }
        });
        jPanel6.add(marcaProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 180, 43));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 180, 10));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 195, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/latiendita.png"))); // NOI18N
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Marca ");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Nombre");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jPanel8.add(jPanel6);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        telefonoProv.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        telefonoProv.setBorder(null);
        telefonoProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoProvKeyTyped(evt);
            }
        });
        jPanel10.add(telefonoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 180, 40));

        codigoProv.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        codigoProv.setBorder(null);
        codigoProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoProvActionPerformed(evt);
            }
        });
        codigoProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoProvKeyTyped(evt);
            }
        });
        jPanel10.add(codigoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 180, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/Enter_ON.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 118, 34));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Codigo Del Proveedor");
        jPanel10.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Telefono");
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));
        jPanel10.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 167, 10));
        jPanel10.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 185, 20));

        bminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        bminimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bminimizarMouseMoved(evt);
            }
        });
        bminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bminimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bminimizarMouseExited(evt);
            }
        });
        jPanel10.add(bminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        bquitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        bquitar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bquitarMouseMoved(evt);
            }
        });
        bquitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bquitarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bquitarMouseExited(evt);
            }
        });
        jPanel10.add(bquitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Agregar Proveedor");
        jPanel10.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jPanel8.add(jPanel10);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boccionesMouseClicked
        AnimationClass producto= new AnimationClass();
        producto.jLabelXRight(-40, 10, 10, 5, jlhomee);

        AnimationClass proveedor= new AnimationClass();
        proveedor.jLabelXRight(-40, 10, 10, 5, jlatras);

        AnimationClass home= new AnimationClass();
        //        home.jLabelXRight(-40, 10, 10, 5, jlhome);

        //<-------------
        AnimationClass productoi= new AnimationClass();
        productoi.jLabelXLeft(10, -40, 10, 5, jlhomee);

        AnimationClass proveedorr= new AnimationClass();
        proveedorr.jLabelXLeft(10, -40, 10, 5, jlatras);

        AnimationClass homer= new AnimationClass();
        //        homer.jLabelXLeft(10, -40, 10, 5, jlhome);
    }//GEN-LAST:event_boccionesMouseClicked

    private void jlhomeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlhomeeMouseClicked
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlhomeeMouseClicked

    private void jlatrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlatrasMouseClicked
        new Productos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlatrasMouseClicked

    private void nombreProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProvActionPerformed

    private void marcaProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaProvActionPerformed

    private void codigoProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoProvActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_codigoProvActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
//        if(cedula.getText().length()==0  || nombretxt.getText().length()==0
//            || nombre.getText().length()==0 || telefono.getText().length()==0
//            || contraseña.getText().length()==0){
//            JOptionPane.showMessageDialog(null,"No pueden haber campos vacíos.");
//        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   // ||nombreProv.getText()==null || marcaProv.getText()==null || telefonoProv.getText()==null
        
   if (codigoProv.getText().isEmpty() || nombreProv.getText().isEmpty() || marcaProv.getText().isEmpty() || telefonoProv.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tienes algún campo vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
       
                if(manejador.verificarCodPro(codigoProv.getText())==true){
                    JOptionPane.showMessageDialog(null, "El codigo ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                }else{
                    manejador.guardarProveedor(codigoProv.getText(), nombreProv.getText(), marcaProv.getText(), telefonoProv.getText());
                    JOptionPane.showMessageDialog(rootPane, "Proveedor guardado correctamente.");
                    codigoProv.setText(" ");
                    nombreProv.setText(" ");
                    marcaProv.setText(" ");
                    telefonoProv.setText(" ");
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bminimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseMoved
        bminimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bminimizarMouseMoved

    private void bminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseClicked
        this.setState(Menu.ICONIFIED);
    }//GEN-LAST:event_bminimizarMouseClicked

    private void bminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseExited
        bminimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bminimizarMouseExited

    private void bquitarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseMoved
        bquitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bquitarMouseMoved

    private void bquitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result= JOptionPane.showConfirmDialog(null,"Desea Salir","Exit", dialog);
        if(result==0){
            System.exit(0);
        }
    }//GEN-LAST:event_bquitarMouseClicked

    private void bquitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseExited
        bquitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bquitarMouseExited

    private void codigoProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoProvKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_codigoProvKeyTyped

    private void telefonoProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoProvKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_telefonoProvKeyTyped

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bminimizar;
    private javax.swing.JLabel bocciones;
    private javax.swing.JLabel bquitar;
    private javax.swing.JTextField codigoProv;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel jlatras;
    private javax.swing.JLabel jlhomee;
    private javax.swing.JTextField marcaProv;
    private javax.swing.JTextField nombreProv;
    private javax.swing.JTextField telefonoProv;
    // End of variables declaration//GEN-END:variables
}
