/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

/**
 *
 * @author PERSONAL
 */
import conexion.Conectar;
import AppPackage.AnimationClass;
import java.util.Locale;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import AppPackage.AnimationClass;

public class AgregarNuevoProducto2 extends javax.swing.JFrame {

     public Conectar manejador = new Conectar(); 

   private Connection connection = null;
   private Statement s = null;
    
    public AgregarNuevoProducto2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
public void ConexionProducto(){
        if (connection != null){
        return;
        }
        
        String url = "jdbc:postgresql://localhost:5433/postgres";
        String password = "iucesmag";
        String user ="postgres";
        try{
            Class.forName("org.postgresql.Driver");
            
            connection = DriverManager.getConnection(url,user,password);
            if(connection != null){
                System.out.println("Conectando a Base de datos.");
            }
            
        }catch (Exception e){
            System.out.println("Problemas de conexión");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        bocciones = new javax.swing.JLabel();
        jlatras = new javax.swing.JLabel();
        jlhome = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        codProducto = new javax.swing.JTextField();
        cedulaUsu = new javax.swing.JTextField();
        stockMax = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        valorPro = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        enterbtn = new javax.swing.JButton();
        bminimizar = new javax.swing.JLabel();
        bquitar = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        stockMin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        codProv = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        nomProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        cantPro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(673, 435));
        setUndecorated(true);

        jPanel2.setMinimumSize(new java.awt.Dimension(673, 435));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setMinimumSize(new java.awt.Dimension(673, 435));
        jPanel3.setPreferredSize(new java.awt.Dimension(673, 342));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(673, 435));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 376));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 32));
        jPanel7.setPreferredSize(new java.awt.Dimension(50, 426));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bocciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Menu_32px_1.png"))); // NOI18N
        bocciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boccionesMouseClicked(evt);
            }
        });
        jPanel7.add(bocciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 22));

        jlatras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlatras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/regresar.png"))); // NOI18N
        jlatras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlatrasMouseClicked(evt);
            }
        });
        jPanel7.add(jlatras, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 50, 40, 30));

        jlhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/inicio.png"))); // NOI18N
        jlhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlhomeMouseClicked(evt);
            }
        });
        jPanel7.add(jlhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 90, 40, 30));

        jPanel5.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setMinimumSize(new java.awt.Dimension(673, 435));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        codProducto.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        codProducto.setBorder(null);
        codProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codProductoActionPerformed(evt);
            }
        });
        jPanel6.add(codProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 180, 43));

        cedulaUsu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cedulaUsu.setBorder(null);
        cedulaUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cedulaUsuActionPerformed(evt);
            }
        });
        jPanel6.add(cedulaUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 43));

        stockMax.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        stockMax.setBorder(null);
        stockMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMaxActionPerformed(evt);
            }
        });
        jPanel6.add(stockMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 43));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Codigo Del progucto ");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Cédula Del cajero");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Stock Máximo");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 10));
        jPanel6.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 10));
        jPanel6.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, 13));

        valorPro.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        valorPro.setBorder(null);
        valorPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorProActionPerformed(evt);
            }
        });
        jPanel6.add(valorPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 43));
        jPanel6.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 13));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Valor Del Producto");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        enterbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/Enter_OFF.png"))); // NOI18N
        enterbtn.setBorder(null);
        enterbtn.setBorderPainted(false);
        enterbtn.setContentAreaFilled(false);
        enterbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/Enter_ON.png"))); // NOI18N
        enterbtn.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/Enter_ON.png"))); // NOI18N
        enterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterbtnActionPerformed(evt);
            }
        });
        jPanel6.add(enterbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 118, 34));

        bminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        bminimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bminimizarMouseMoved(evt);
            }
        });
        bminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bminimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bminimizarMouseExited(evt);
            }
        });
        jPanel6.add(bminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        bquitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        bquitar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bquitarMouseMoved(evt);
            }
        });
        bquitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bquitarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bquitarMouseExited(evt);
            }
        });
        jPanel6.add(bquitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, -1, -1));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 180, 13));

        stockMin.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        stockMin.setBorder(null);
        stockMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockMinActionPerformed(evt);
            }
        });
        jPanel6.add(stockMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 180, 43));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setText("Stock Minimo:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 180, 10));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Código Del Proveedor");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        codProv.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        codProv.setBorder(null);
        codProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codProvActionPerformed(evt);
            }
        });
        jPanel6.add(codProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 180, 43));
        jPanel6.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 180, 10));

        nomProducto.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        nomProducto.setBorder(null);
        nomProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomProductoActionPerformed(evt);
            }
        });
        jPanel6.add(nomProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 180, 43));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Nombre");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));
        jPanel6.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 180, 10));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Cantidad Del Producto");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 150, -1));

        cantPro.setBorder(null);
        jPanel6.add(cantPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 180, 40));

        jPanel8.add(jPanel6);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bminimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseMoved
        bminimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bminimizarMouseMoved

    private void bminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseClicked
        this.setState(Menu.ICONIFIED);
    }//GEN-LAST:event_bminimizarMouseClicked

    private void bminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseExited
        bminimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bminimizarMouseExited

    private void bquitarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseMoved
        bquitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bquitarMouseMoved

    private void bquitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result= JOptionPane.showConfirmDialog(null,"Desea Salir","Exit", dialog);
        if(result==0){
            System.exit(0);
        }
    }//GEN-LAST:event_bquitarMouseClicked

    private void bquitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseExited
        bquitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bquitarMouseExited

    private void boccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boccionesMouseClicked
        AnimationClass producto= new AnimationClass();
        producto.jLabelXRight(-40, 10, 10, 5, jlatras);

        AnimationClass proveedor= new AnimationClass();
        proveedor.jLabelXRight(-40, 10, 10, 5, jlatras);

        AnimationClass home= new AnimationClass();
        home.jLabelXRight(-40, 10, 10, 5, jlatras);

        //<-------------
        AnimationClass productoi= new AnimationClass();
        productoi.jLabelXLeft(10, -40, 10, 5, jlatras);

        AnimationClass proveedorr= new AnimationClass();
        proveedorr.jLabelXLeft(10, -40, 10, 5, jlatras);

        AnimationClass homer= new AnimationClass();
        homer.jLabelXLeft(10, -40, 10, 5, jlatras);
    }//GEN-LAST:event_boccionesMouseClicked

    private void jlatrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlatrasMouseClicked
        new Productos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlatrasMouseClicked

    private void codProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codProductoActionPerformed

    private void cedulaUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cedulaUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cedulaUsuActionPerformed

    private void stockMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMaxActionPerformed

    private void valorProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorProActionPerformed

    private void stockMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockMinActionPerformed

    private void codProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codProvActionPerformed

    private void nomProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomProductoActionPerformed

    private void jlhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlhomeMouseClicked
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlhomeMouseClicked

    private void enterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterbtnActionPerformed
        
        if(  codProducto.getText().isEmpty()||nomProducto.getText().isEmpty()|| codProv.getText().isEmpty()||cedulaUsu.getText().isEmpty()||cantPro.getText().isEmpty()||valorPro.getText().isEmpty()||stockMax.getText().isEmpty()||stockMin.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Tienes algún campo vacío." ,"Error",JOptionPane.ERROR_MESSAGE);
        }else{
        
            manejador.guardarPro(codProducto.getText(), nomProducto.getText(), codProv.getText(), cedulaUsu.getText(), Integer.parseInt(cantPro.getText()), Integer.parseInt(valorPro.getText()), Integer.parseInt(stockMax.getText()), Integer.parseInt(stockMin.getText()));
            JOptionPane.showMessageDialog(rootPane, "Producto guardado correctamente.");
            codProducto.setText(" ");
            nomProducto.setText(" ");
            codProv.setText(" ");
            cedulaUsu.setText(" ");
            cantPro.setText(" ");
            valorPro.setText(" ");
            stockMax.setText(" ");
            stockMin.setText(" ");
        }
    }//GEN-LAST:event_enterbtnActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bminimizar;
    private javax.swing.JLabel bocciones;
    private javax.swing.JLabel bquitar;
    private javax.swing.JTextField cantPro;
    private javax.swing.JTextField cedulaUsu;
    private javax.swing.JTextField codProducto;
    private javax.swing.JTextField codProv;
    private javax.swing.JButton enterbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jlatras;
    private javax.swing.JLabel jlhome;
    private javax.swing.JTextField nomProducto;
    private javax.swing.JTextField stockMax;
    private javax.swing.JTextField stockMin;
    private javax.swing.JTextField valorPro;
    // End of variables declaration//GEN-END:variables
}
