/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author PERSONAL
 */
public class menu2 extends javax.swing.JFrame {

    /**
     * Creates new form iterfaz
     */
    public menu2() {
        initComponents();
        ImageIcon imagen= new ImageIcon("");
        this.setLocationRelativeTo(null);
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bminimizar = new javax.swing.JLabel();
        bquitar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bproductos = new javax.swing.JPanel();
        jlaver = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        bventas = new javax.swing.JPanel();
        bproductos2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/latiendita.png"))); // NOI18N

        bminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        bminimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bminimizarMouseMoved(evt);
            }
        });
        bminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bminimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bminimizarMouseExited(evt);
            }
        });

        bquitar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bquitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        bquitar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bquitarMouseMoved(evt);
            }
        });
        bquitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bquitarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bquitarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(bminimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bquitar))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bquitar)
                    .addComponent(bminimizar))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bproductos.setBackground(new java.awt.Color(255, 255, 255));
        bproductos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bproductosMouseMoved(evt);
            }
        });
        bproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bproductosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bproductosMouseExited(evt);
            }
        });

        jlaver.setBackground(new java.awt.Color(255, 255, 255));
        jlaver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlaver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/checklist-1295319_960_720 (1).png"))); // NOI18N
        jlaver.setOpaque(true);
        jlaver.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jlaverMouseMoved(evt);
            }
        });
        jlaver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlaverMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlaverMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Productos");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bproductosLayout = new javax.swing.GroupLayout(bproductos);
        bproductos.setLayout(bproductosLayout);
        bproductosLayout.setHorizontalGroup(
            bproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bproductosLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(bproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bproductosLayout.createSequentialGroup()
                        .addComponent(jlaver)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bproductosLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(25, 25, 25))))
        );
        bproductosLayout.setVerticalGroup(
            bproductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bproductosLayout.createSequentialGroup()
                .addComponent(jlaver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel4.add(bproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jPanel3.add(jPanel4);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bventas.setBackground(new java.awt.Color(255, 255, 255));
        bventas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bventasMouseMoved(evt);
            }
        });
        bventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bventasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bventasMouseExited(evt);
            }
        });

        bproductos2.setBackground(new java.awt.Color(255, 255, 255));
        bproductos2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bproductos2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/primer.png"))); // NOI18N
        bproductos2.setOpaque(true);
        bproductos2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bproductos2MouseMoved(evt);
            }
        });
        bproductos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bproductos2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bproductos2MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ventas");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bventasLayout = new javax.swing.GroupLayout(bventas);
        bventas.setLayout(bventasLayout);
        bventasLayout.setHorizontalGroup(
            bventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bventasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bproductos2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bventasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(30, 30, 30))
        );
        bventasLayout.setVerticalGroup(
            bventasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bventasLayout.createSequentialGroup()
                .addComponent(bproductos2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel11.add(bventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel2.setText("ACERCA DE");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel6);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseClicked
        this.setState(menu2.ICONIFIED);
    }//GEN-LAST:event_bminimizarMouseClicked

    private void bquitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result= JOptionPane.showConfirmDialog(null,"Desea Salir","Exit", dialog);
        if(result==0){
            System.exit(0);
        }
        
    
    }//GEN-LAST:event_bquitarMouseClicked

    private void jlaverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlaverMouseMoved
     bproductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jlaverMouseMoved

    private void bproductos2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bproductos2MouseMoved
        bventas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bproductos2MouseMoved

    private void bproductosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bproductosMouseMoved
        bproductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bproductosMouseMoved

    private void bproductosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bproductosMouseExited
        bproductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bproductosMouseExited

    private void jlaverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlaverMouseExited
        bproductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_jlaverMouseExited

    private void bventasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bventasMouseMoved
        bventas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bventasMouseMoved

    private void bventasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bventasMouseExited
        bventas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bventasMouseExited

    private void bproductos2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bproductos2MouseExited
       bventas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bproductos2MouseExited

    private void bminimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseMoved
       bminimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bminimizarMouseMoved

    private void bminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseExited
       bminimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bminimizarMouseExited

    private void bquitarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseMoved
       bquitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bquitarMouseMoved

    private void bquitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseExited
     bquitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bquitarMouseExited

    private void bproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bproductosMouseClicked
          new Productos().setVisible(true);
          this.setVisible(false);
    }//GEN-LAST:event_bproductosMouseClicked

    private void jlaverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlaverMouseClicked
         new Productos().setVisible(true);
          this.setVisible(false);
    }//GEN-LAST:event_jlaverMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
         new Productos().setVisible(true);
          this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void bventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bventasMouseClicked
        new Ventas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bventasMouseClicked

    private void bproductos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bproductos2MouseClicked
        new Ventas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bproductos2MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        new Ventas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        String nl= System.getProperty("line.separator");
        JOptionPane.showMessageDialog(null,"Programa Realizado por: "+nl+" -Daniel Esteban Madroñero "+nl+
                 "-Juan Pablo Solarte "+nl+ "-Mario Andres Argoti "+nl+ "-Christian Daniel Goyes "+nl+ "Bajo el nombre de la empresa "+nl+ "Team P & I (Proteccion e Informacion)"
                +nl+ "Subsidiado bajo la auditoria de : "+nl+ " Institucion Universitaria CESMAG"+nl+ "Version 2.18");
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bminimizar;
    private javax.swing.JPanel bproductos;
    private javax.swing.JLabel bproductos2;
    private javax.swing.JLabel bquitar;
    private javax.swing.JPanel bventas;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jlaver;
    // End of variables declaration//GEN-END:variables
}
