/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package prueba;
import AppPackage.AnimationClass;
import conexion.Conectar;

import constructores.variablesPagar;
import constructores.variablestablas;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author PERSONAL
 */
public class Ventas extends javax.swing.JFrame {
    public Conectar manejador= new Conectar();
    private double tsiniva=0;
 
    
variablestablas vt;
int clic_tabla = 1;

    /** Creates new form Ventas */
    public Ventas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) tablaprocomp.getModel();
        int a = tablaprocomp.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        }
    }
     public void eliminartcompra(){
        DefaultTableModel tb = (DefaultTableModel) tablacompra.getModel();
        int a = tablacompra.getRowCount()-1;
        for (int i = a; i >= 0; i--) {           
        tb.removeRow(tb.getRowCount()-1);
        }
    }
    public void mostrardtabla(){
       DefaultTableModel dtm;
       ResultSetMetaData rsmd;
        try{ 
           
            ResultSet sr= manejador.mostrartabla.executeQuery();
            rsmd=sr.getMetaData();
            ArrayList<Object[]> data =new ArrayList<>();
            while(sr.next()){
                Object[] rows =new Object[rsmd.getColumnCount()];
                for (int i = 0; i < rows.length; i++) {
                    rows[i]=sr.getObject(i+1);
                }
                data.add(rows);
            }
             dtm = (DefaultTableModel)this.tablaprocomp.getModel();
             for (int i = 0; i < data.size(); i++) {
                dtm.addRow(data.get(i));
                
            }
             
//            msn="exito";
            
        }catch(SQLException ex){
            ex.printStackTrace();
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        bocciones = new javax.swing.JLabel();
        jlhome = new javax.swing.JLabel();
        jlagregarusu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bminimizar = new javax.swing.JLabel();
        bquitar = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jTextField16 = new javax.swing.JTextField();
        totaliva = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        NomPro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        CodPro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        tcantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        beliminar = new javax.swing.JLabel();
        bminimizar2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacompra = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaprocomp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel5.setPreferredSize(new java.awt.Dimension(673, 435));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 32));
        jPanel7.setPreferredSize(new java.awt.Dimension(50, 426));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bocciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Menu_32px_1.png"))); // NOI18N
        bocciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boccionesMouseClicked(evt);
            }
        });
        jPanel7.add(bocciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 22));

        jlhome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/inicio.png"))); // NOI18N
        jlhome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlhomeMouseClicked(evt);
            }
        });
        jPanel7.add(jlhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 50, 40, 30));

        jlagregarusu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlagregarusu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/add-user_icon-icons.com_55050_1.png"))); // NOI18N
        jlagregarusu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlagregarusuMouseClicked(evt);
            }
        });
        jPanel7.add(jlagregarusu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 90, 40, 30));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 435));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(273, 376));
        jPanel1.setPreferredSize(new java.awt.Dimension(410, 348));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setMinimumSize(new java.awt.Dimension(273, 435));
        jPanel4.setPreferredSize(new java.awt.Dimension(276, 435));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        bminimizar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bminimizarMouseMoved(evt);
            }
        });
        bminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bminimizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bminimizarMouseExited(evt);
            }
        });
        jPanel4.add(bminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        bquitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        bquitar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bquitarMouseMoved(evt);
            }
        });
        bquitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bquitarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bquitarMouseExited(evt);
            }
        });
        jPanel4.add(bquitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Regreso ");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 130, -1));

        jTextField13.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField13.setText("0");
        jTextField13.setBorder(null);
        jTextField13.setEnabled(false);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField13KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 90, 20));
        jPanel4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, -1));
        jPanel4.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 80, 10));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cantidad a Pagar ");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setText("Total ");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, -1));
        jPanel4.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 70, 20));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel15.setText("Total + IVA");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 100, -1));
        jPanel4.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, 20));

        jTextField16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField16.setText("0");
        jTextField16.setBorder(null);
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField16KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField16KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 20));

        totaliva.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        totaliva.setText("0");
        totaliva.setBorder(null);
        totaliva.setEnabled(false);
        totaliva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalivaActionPerformed(evt);
            }
        });
        totaliva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalivaKeyTyped(evt);
            }
        });
        jPanel4.add(totaliva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 70, 20));

        jTextField18.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jTextField18.setBorder(null);
        jTextField18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField18MouseClicked(evt);
            }
        });
        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField18KeyTyped(evt);
            }
        });
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, 20));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/porcentaje2_2.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 70, 50));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/plata.png"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 50));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Calculator_32px.png"))); // NOI18N
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 70, 50));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PAGAR");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 90, 40));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/primer.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, 110));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Pago");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 13, -1, 30));

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomPro.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        NomPro.setBorder(null);
        NomPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomProActionPerformed(evt);
            }
        });
        NomPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NomProKeyTyped(evt);
            }
        });
        jPanel6.add(NomPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 110, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Nombre");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 60, -1));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 120, 20));
        jPanel6.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 100, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Codigo");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 60, -1));

        CodPro.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        CodPro.setBorder(null);
        CodPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodProActionPerformed(evt);
            }
        });
        CodPro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CodProKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodProKeyTyped(evt);
            }
        });
        jPanel6.add(CodPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 110, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Lista De Compras");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        jPanel6.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 40, 10));

        tcantidad.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        tcantidad.setText("1");
        tcantidad.setBorder(null);
        tcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcantidadActionPerformed(evt);
            }
        });
        tcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tcantidadKeyTyped(evt);
            }
        });
        jPanel6.add(tcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 30, 20));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Cantidad ");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 60, 20));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/icons8_Search_32px.png"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, 70, 50));

        beliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/quitar_1.png"))); // NOI18N
        beliminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                beliminarMouseMoved(evt);
            }
        });
        beliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beliminarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                beliminarMouseExited(evt);
            }
        });
        jPanel6.add(beliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, -1, -1));

        bminimizar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prueba/imagenes/carrito.png"))); // NOI18N
        bminimizar2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bminimizar2MouseMoved(evt);
            }
        });
        bminimizar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bminimizar2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bminimizar2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bminimizar2MousePressed(evt);
            }
        });
        jPanel6.add(bminimizar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 50, 40));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setText("Lista De Productos");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        tablacompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablacompra.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        tablacompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Valor", "Cant Disp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablacompra.setToolTipText("");
        tablacompra.setGridColor(new java.awt.Color(255, 255, 255));
        tablacompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacompra);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 230, 130));

        tablaprocomp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablaprocomp.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        tablaprocomp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nom", "Cont", "Valor", "Max", "Min"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaprocomp.setToolTipText("");
        tablaprocomp.setGridColor(new java.awt.Color(255, 255, 255));
        tablaprocomp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaprocompMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaprocomp);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 250, 110));

        jPanel1.add(jPanel6, java.awt.BorderLayout.LINE_START);

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 623, 435));

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bquitarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseExited
        bquitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bquitarMouseExited

    private void bquitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea Salir", "Exit", dialog);
        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_bquitarMouseClicked

    private void bquitarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bquitarMouseMoved
        bquitar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bquitarMouseMoved

    private void bminimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseExited
        bminimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_bminimizarMouseExited

    private void bminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseClicked
        this.setState(Menu.ICONIFIED);
    }//GEN-LAST:event_bminimizarMouseClicked

    private void bminimizarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizarMouseMoved
        bminimizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bminimizarMouseMoved

    private void jlhomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlhomeMouseClicked
        new Menu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlhomeMouseClicked

    private void boccionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boccionesMouseClicked
        AnimationClass producto = new AnimationClass();
        producto.jLabelXRight(-40, 10, 10, 5, jlhome);

        AnimationClass proveedor = new AnimationClass();
        proveedor.jLabelXRight(-40, 10, 10, 5, jlagregarusu);

        AnimationClass home = new AnimationClass();
        home.jLabelXRight(-40, 10, 10, 5, jlhome);

        //<-------------
        AnimationClass productoi = new AnimationClass();
        productoi.jLabelXLeft(10, -40, 10, 5, jlhome);

        AnimationClass proveedorr = new AnimationClass();
        proveedorr.jLabelXLeft(10, -40, 10, 5, jlagregarusu);

        AnimationClass homer= new AnimationClass();
        homer.jLabelXLeft(10, -40, 10, 5, jlhome);
    }//GEN-LAST:event_boccionesMouseClicked

    private void NomProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomProActionPerformed

    private void CodProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodProActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CodProActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void tcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcantidadActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void totalivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalivaActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jlagregarusuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlagregarusuMouseClicked
               new agregarProo().setVisible(true);
               this.setVisible(false);
    }//GEN-LAST:event_jlagregarusuMouseClicked

    private void beliminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beliminarMouseMoved
       beliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_beliminarMouseMoved

    private void beliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beliminarMouseClicked
        DefaultTableModel tablitamodelo= (DefaultTableModel) tablacompra.getModel();
        if (tablacompra.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(null,"Necesita seleccionar un elemento." ,"Error",JOptionPane.ERROR_MESSAGE);
        }else{
            int i=tablacompra.getSelectedRow();
        tablitamodelo.removeRow(i);
        }
        
      
    }//GEN-LAST:event_beliminarMouseClicked

    private void beliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beliminarMouseExited
  beliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));        // TODO add your handling code here:
    }//GEN-LAST:event_beliminarMouseExited

    private void bminimizar2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizar2MouseMoved
        bminimizar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_bminimizar2MouseMoved

    private void bminimizar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizar2MouseClicked
        int i = tablaprocomp.getSelectedRow();

        if (tablaprocomp.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Necesita seleccionar un elemento.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (tcantidad.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Especifique la cantidad de unidades.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if (Integer.parseInt(tcantidad.getText()) == 0) {
                JOptionPane.showMessageDialog(null, "La cantidad de unidades debe ser mayor a cero", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (Integer.parseInt(tcantidad.getText()) > (Integer) tablaprocomp.getValueAt(i, 2)) {
                    if ((Integer) tablaprocomp.getValueAt(i, 2) == 0) {
                        JOptionPane.showMessageDialog(null, "No hay producto existente.", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "Solo hay en existencia " + tablaprocomp.getValueAt(i, 2) + " Unidades", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    //tablitamodelo.addRow(new Object[]{(String)(tablaprocomp.getValueAt(i, 1)),Integer.parseInt(tcantidad.getText()),Integer.parseInt((String)(tablaprocomp.getValueAt(i, 3)))});

                    DefaultTableModel tablitamodelo = (DefaultTableModel) tablacompra.getModel();
                    tablitamodelo.addRow(new Object[]{tablaprocomp.getValueAt(i, 0), tablaprocomp.getValueAt(i, 1), tcantidad.getText(), tablaprocomp.getValueAt(i, 3), tablaprocomp.getValueAt(i, 2)});
                    tsiniva = ((int) tablaprocomp.getValueAt(i, 3)) * (Integer.parseInt(tcantidad.getText())) + tsiniva;

                    jTextField16.setText("" + tsiniva);
                    double total = (tsiniva * 0.19) + tsiniva;
                    totaliva.setText("" + total);
                }
            }
        }
    }//GEN-LAST:event_bminimizar2MouseClicked

    private void bminimizar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizar2MouseExited
        bminimizar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))); 
    }//GEN-LAST:event_bminimizar2MouseExited

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
       jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153))); 
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
      jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255))); 
    }//GEN-LAST:event_jLabel1MouseExited

    private void bminimizar2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bminimizar2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bminimizar2MousePressed

    private void CodProKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodProKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CodProKeyPressed

    private void CodProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodProKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_CodProKeyTyped

    private void jTextField16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_jTextField16KeyTyped

    private void totalivaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalivaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_totalivaKeyTyped

    private void jTextField18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_jTextField18KeyTyped

    private void jTextField13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_jTextField13KeyTyped

    private void tcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tcantidadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_tcantidadKeyTyped

    private void NomProKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomProKeyTyped
        String nProducto= NomPro.getText();
        
    }//GEN-LAST:event_NomProKeyTyped

    private void jTextField16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyPressed
        // TODO add your handling code here:
//        jTextField17.setText(" ");
//        double iv=0;
//       int i=Integer.parseInt(jTextField16.getText());
//       double p = i*0.19;
//       iv=i+p;
//       jTextField17.setText(" " +iv);
    }//GEN-LAST:event_jTextField16KeyPressed

    private void jTextField18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField18MouseClicked
        // TODO add your handling code here:
        jTextField18.setText("");
    }//GEN-LAST:event_jTextField18MouseClicked

    private void tablacompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacompraMouseClicked

    }//GEN-LAST:event_tablacompraMouseClicked

    private void tablaprocompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaprocompMouseClicked
        int i=tablaprocomp.getSelectedRow();
        NomPro.setText((String)(tablaprocomp.getValueAt(i, 1)));
        CodPro.setText((String)(tablaprocomp.getValueAt(i, 0)));
    }//GEN-LAST:event_tablaprocompMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        mostrardtabla();
    }//GEN-LAST:event_formWindowActivated

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      
//        int cant =(int) tablalcomp.getValueAt(0, 2);
//        String cod = ""+(int) tablalcomp.getValueAt(0, 0);
//        manejador.pagar(cant,cod );
DefaultTableModel model = (DefaultTableModel) tablacompra.getModel();
DefaultTableModel model2 = (DefaultTableModel) tablacompra.getModel();
        eliminar();
        mostrardtabla();       
        int cantidad=0;
        
       
//Integer.parseInt(jTextField18.getText());
        if (jTextField18.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Tiene que ingresar una cifra en La cantidad a pagar." ,"Error",JOptionPane.ERROR_MESSAGE);
        }else{
        if(Double.parseDouble(jTextField18.getText())<Double.parseDouble(totaliva.getText())){
            JOptionPane.showMessageDialog(null,"El valor debe ser mayor al total + el iva." ,"Error",JOptionPane.ERROR_MESSAGE);
        }else{
            
        for (int i = 0; i < model.getRowCount(); i++) {
        cantidad= (Integer) model.getValueAt(i,4) -Integer.parseInt((String)model.getValueAt(i, 2));
        manejador.pagar(cantidad, (String)model.getValueAt(i,0));
//         manejador.guardarVenta((String)model.getValueAt(i,0),);
        }
        JOptionPane.showMessageDialog(null,"Venta Hecha satisfactoriamente :3.");
       
        eliminar();
        mostrardtabla();
        eliminartcompra();
        jTextField13.setText(""+(Integer.parseInt(jTextField18.getText())-Double.parseDouble(totaliva.getText())));
        }
}
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodPro;
    private javax.swing.JTextField NomPro;
    private javax.swing.JLabel beliminar;
    private javax.swing.JLabel bminimizar;
    private javax.swing.JLabel bminimizar2;
    private javax.swing.JLabel bocciones;
    private javax.swing.JLabel bquitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JLabel jlagregarusu;
    private javax.swing.JLabel jlhome;
    private javax.swing.JTable tablacompra;
    private javax.swing.JTable tablaprocomp;
    private javax.swing.JTextField tcantidad;
    private javax.swing.JTextField totaliva;
    // End of variables declaration//GEN-END:variables

}
